### PR TITLE
Command Documentation Updates

### PR DESCRIPTION
**Pull request by M4aXim**

### CODE REVIEW

**Review by plun1331 — CHANGES_REQUESTED** [review]
format it properly and make sure the commands actually exist

**Comment by M4aXim** [comment]
ahh fine

**Review by M4aXim — COMMENTED** [review]
TIme to do it

**Review by M4aXim — COMMENTED** [review]
Done

**Comment by M4aXim** [comment]
If you need anything else please type here

**Review by M4aXim — COMMENTED** [review]
Few changes were made for example adding games section

**Comment by M4aXim** [comment]
Last edit hopefully

**Comment by M4axim** [comment]
Had to do it :)

**Comment by plun1331** [comment]
Still doesn't follow the format; see https://github.com/SkyKings-Guild/SkyKings/blob/main/commands.md?plain=1#L14-L48 for the proper format.

**Comment by M4aXim** [comment]
You are killing me smh

**Comment by M4aXim** [comment]
I am gonna finish it tommorow once i get on pc

**Pull request closed without merging**
